version: "3"

networks:
  hyc-demo:
    name: hyc-demo
    driver: bridge

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    networks:
      - hyc-demo

  gitea:
    image: gitea/gitea:1.12.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - hyc-demo
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    container_name: server
    command: server
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_TOKEN=${K3S_TOKEN:?err}
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    networks:
      - hyc-demo
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml
      # This is just so that we get the kubeconfig file out
      - .:/output
    ports:
      - 6443:6443

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    container_name: agent
    tmpfs:
      - /run
      - /var/run
    privileged: true
    volumes:
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml
    networks:
      - hyc-demo
    environment:
      - K3S_URL=https://server:6443
      - K3S_TOKEN=${K3S_TOKEN:?err}

volumes:
  k3s-server: {}
